module.exports = {
	START_DAY: 11,
	END_DAY: 31,
	EVENT_LIST_CARD_SELECTOR: ".seriesEventCardModule__target",
	SELECTORS: {
		MONTH: 1,
		YEAR: 2022,
		TITLE_SELECTOR: "section.eventHero h1.eventHero__title",
		POSTER_SELECTOR: "section.eventHero figure.eventHero__image > img",
		LOCATION_SELECTOR: "section.eventHero > div > article > div.eventHero__intro > p:nth-child(1)",
		DATE_SELECTOR: "section.eventHero span.eventHero__date",
		TIME_SELECTOR: "section.eventHero span.eventHero__time",
		SINGLE_DESCRIPTION_SELECTOR: "div.eventMain__body > h3 + p",
		SINGLE_DIRECTOR_SELECTOR: "section.eventDetailBar ul.eventDetailBar__list > li:nth-child(3)",
		DOUBLE_TITLE_SELECTOR: "section.eventMain div.eventMain__body > p span:first-child",
		DOUBLE_DIRECTOR_SELECTOR: "section.eventMain div.eventMain__body > hr + p > span:first-child"
	},
	SCREENING_URLS: [
		'https://www.americancinematheque.com/now-showing/the-perfume-of-the-lady-in-black/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-5/',
		'https://www.americancinematheque.com/now-showing/billie-eilish-the-worlds-a-little-blurry-the-september-issue/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-6/',
		'https://www.americancinematheque.com/now-showing/rivers-edge-2/',
		'https://www.americancinematheque.com/now-showing/spencer-the-shining/',
		'https://www.americancinematheque.com/now-showing/gummo-2/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-7/',
		'https://www.americancinematheque.com/now-showing/west-side-story-aero-1-13-730pm/',
		'https://www.americancinematheque.com/now-showing/spencer/',
		'https://www.americancinematheque.com/now-showing/a-woman-under-the-influence/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-6/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-8/',
		'https://www.americancinematheque.com/now-showing/malcolm-x-2/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-5/',
		'https://www.americancinematheque.com/now-showing/friday-night-frights-presents-mandy/',
		'https://www.americancinematheque.com/now-showing/miracle-mile/',
		'https://www.americancinematheque.com/now-showing/vertigo/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-4/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-los-feliz-1-16-7pm/',
		'https://www.americancinematheque.com/now-showing/lawrence-of-arabia-4/',
		'https://www.americancinematheque.com/now-showing/girl-in-room-2a/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-9/',
		'https://www.americancinematheque.com/now-showing/munich/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-3/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-2/',
		'https://www.americancinematheque.com/now-showing/lincoln/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-los-feliz-1-21-1-30pm/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-10/',
		'https://www.americancinematheque.com/now-showing/nightmare-alley-bw-1/',
		'https://www.americancinematheque.com/now-showing/volcano/',
		'https://www.americancinematheque.com/now-showing/nightmare-alley-bw-2/',
		'https://www.americancinematheque.com/now-showing/the-game/',
		'https://www.americancinematheque.com/now-showing/ace-in-the-hole/',
		'https://www.americancinematheque.com/now-showing/chess-of-the-wind-3/',
		'https://www.americancinematheque.com/now-showing/nightmare-alley-bw-3/',
		'https://www.americancinematheque.com/now-showing/days-of-heaven-2/',
		'https://www.americancinematheque.com/now-showing/the-corruption-of-chris-miller/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-lf3-1-24-1000pm/',
		'https://www.americancinematheque.com/now-showing/the-400-blows/',
		'https://www.americancinematheque.com/now-showing/last-and-first-men-los-feliz-1-28-1-30pm/',
		'https://www.americancinematheque.com/now-showing/out-of-the-blue-lf3-1-28-400pm/',
		'https://www.americancinematheque.com/now-showing/them/',
		'https://www.americancinematheque.com/now-showing/chess-of-the-wind-4/',
		'https://www.americancinematheque.com/now-showing/something-creeping-in-the-dark/'
	]
};