module.exports = {
	START_DAY: 16,
	END_DAY: 31,
	EVENT_LIST_CARD_SELECTOR: ".seriesEventCardModule__target",
	SELECTORS: {
		MONTH: 3,
		YEAR: 2022,
		TITLE_SELECTOR: "section.eventHero h1.eventHero__title",
		POSTER_SELECTOR: "section.eventHero figure.eventHero__image > img",
		LOCATION_SELECTOR: "section.eventHero > div > article > div.eventHero__intro > p:nth-child(1)",
		DATE_SELECTOR: "section.eventHero span.eventHero__date",
		TIME_SELECTOR: "section.eventHero span.eventHero__time",
		SINGLE_DESCRIPTION_SELECTOR: "div.eventMain__body > h3 + p",
		SINGLE_DIRECTOR_SELECTOR: "section.eventDetailBar ul.eventDetailBar__list > li:nth-child(3)",
		DOUBLE_FIRST_SELECTOR: "section.eventMain div.eventMain__body > p span:first-child",
		DOUBLE_SECOND_SELECTOR: "section.eventMain div.eventMain__body > hr + p > span:first-child"
	},
	SCREENING_URLS: [
		// 'https://www.americancinematheque.com/now-showing/destroy-she-said-3-1-22/',
		// 'https://www.americancinematheque.com/now-showing/dont-look-up-3-1-2022/',
		// 'https://www.americancinematheque.com/now-showing/je-taime-je-taime-3-1-22/',
		// 'https://www.americancinematheque.com/now-showing/dune-3-2-22/',
		// 'https://www.americancinematheque.com/now-showing/hudas-salon-3-2-2022/',
		// 'https://www.americancinematheque.com/now-showing/y-tu-mama-tambien-3-2-22/',
		// 'https://www.americancinematheque.com/now-showing/diva-3-3-2022/',
		// 'https://www.americancinematheque.com/now-showing/deliverance-march-3-2022/',
		// 'https://www.americancinematheque.com/now-showing/sabata-march-4-2022/',
		// 'https://www.americancinematheque.com/now-showing/cool-hand-luke-march-4-2022/',
		// 'https://www.americancinematheque.com/now-showing/king-richard-rocky-3-4-22/',
		// 'https://www.americancinematheque.com/now-showing/deliverance-3-4-2022/',
		// 'https://www.americancinematheque.com/now-showing/o-brother-where-art-thou-march-4-2022/',
		// 'https://www.americancinematheque.com/now-showing/a-most-violent-year-3-5-2022/',
		// 'https://www.americancinematheque.com/now-showing/house-of-gucci-3-5-22/',
		// 'https://www.americancinematheque.com/now-showing/star-trek-vi-the-undiscovered-country-march-5-2022/',
		// 'https://www.americancinematheque.com/now-showing/cool-hand-luke-3-5-2022/',
		// 'https://www.americancinematheque.com/now-showing/west-side-story-march-5-2022/',
		// 'https://www.americancinematheque.com/now-showing/diva-3-5-2022/',
		// 'https://www.americancinematheque.com/now-showing/stage-fright-3-6-22/',
		// 'https://www.americancinematheque.com/now-showing/lord-miller-gaku-our-sound-3-6-22/',
		// 'https://www.americancinematheque.com/now-showing/no-time-to-die-3-6-2022/',
		// 'https://www.americancinematheque.com/now-showing/destroy-she-said-le-navire-night-3-6-22/',
		// 'https://www.americancinematheque.com/now-showing/werewolf-of-washington-3-6-2022/',
		// 'https://www.americancinematheque.com/now-showing/tribute-to-the-crafts/', DELETE
		// 'https://www.americancinematheque.com/now-showing/cinematic-void-presents-patrick-still-lives/',
		// 'https://www.americancinematheque.com/now-showing/o-brother-where-art-thou-3-7-22/',
		// 'https://www.americancinematheque.com/now-showing/all-the-old-knives-3-8-22/',
		// 'https://www.americancinematheque.com/now-showing/le-camion-3-8-22/',
		// 'https://www.americancinematheque.com/now-showing/chariots-of-fire-march-9-2022/', DELETE
		// 'https://www.americancinematheque.com/now-showing/my-blueberry-nights-3-9-22/',
		// 'https://www.americancinematheque.com/now-showing/the-conversation-3-10-22/',
		// 'https://www.americancinematheque.com/now-showing/sabata-3-10-22/',
		// 'https://www.americancinematheque.com/now-showing/sisters-in-arms-3-11-22/',
		// 'https://www.americancinematheque.com/now-showing/the-cats-meow-march-11-2022/',
		// 'https://www.americancinematheque.com/now-showing/friday-night-frights-presents-the-nest/', DELETE
		// 'https://www.americancinematheque.com/now-showing/crimson-peak-3-12-2022/',
		// 'https://www.americancinematheque.com/now-showing/the-bloody-child-march-12-2022/',
		// 'https://www.americancinematheque.com/now-showing/lunana-a-yak-3-12-2022/',
		// 'https://www.americancinematheque.com/now-showing/the-conversation-3-12-22/',
		// 'https://www.americancinematheque.com/now-showing/the-tragedy-of-macbeth-3-13-22/',
		// 'https://www.americancinematheque.com/now-showing/lord-miller-muppet-movie-3-13-22/',
		// 'https://www.americancinematheque.com/now-showing/the-green-ray-3-13-22/',
		// 'https://www.americancinematheque.com/now-showing/mulholland-drive-sunset-boulevard-3-13-22/',
		// 'https://www.americancinematheque.com/now-showing/coming-apart-3-13-2022/',
		// 'https://www.americancinematheque.com/now-showing/cinematic-void-presents-phantasm-ii-march-14-2022/',
		// 'https://www.americancinematheque.com/now-showing/metropolis-3-14-22/', DELETE
		// 'https://www.americancinematheque.com/now-showing/a-hard-days-night-march-15-2022/',
		// 'https://www.americancinematheque.com/now-showing/le-navire-night-3-15-22/',
		// 'https://www.americancinematheque.com/now-showing/million-dollar-march-16-2022/', DELETE
		// 'https://www.americancinematheque.com/now-showing/les-rendez-vous-danna-3-16-22/',
		// 'https://www.americancinematheque.com/now-showing/the-conversation-3-17-22/',
		// 'https://www.americancinematheque.com/now-showing/queen-of-diamonds-march-17-2022/',
		// 'https://www.americancinematheque.com/now-showing/vagabond-3-18-22/',
		// 'https://www.americancinematheque.com/now-showing/wheel-and-fantasy-3-18-22/',
		// 'https://www.americancinematheque.com/now-showing/hamaguchi-all-that-heaven-3-18-22/',
		// 'https://www.americancinematheque.com/now-showing/take-shelter-3-19-2022/',
		// 'https://www.americancinematheque.com/now-showing/magdalena-viraga-march-19-2022/',
		// 'https://www.americancinematheque.com/now-showing/tammy-faye-tree-of-life-3-19-2022/',
		// 'https://www.americancinematheque.com/now-showing/joan-of-arc-of-mongolia-3-19-22/',
		// 'https://www.americancinematheque.com/now-showing/the-conversation/',
		// 'https://www.americancinematheque.com/now-showing/laraine-newman-presents-the-women/',
		// 'https://www.americancinematheque.com/now-showing/drive-my-car-2-march-20-2022/',
		// 'https://www.americancinematheque.com/now-showing/nights-of-cabiria-3-20-22/',
		// 'https://www.americancinematheque.com/now-showing/happy-hour-march-20-2022/',
		// 'https://www.americancinematheque.com/now-showing/priscilla-queen-of-the-desert-3-20-22/',
		// 'https://www.americancinematheque.com/now-showing/goodbye-dragon-inn-3-20-2022/',
		// 'https://www.americancinematheque.com/now-showing/india-song-3-22-22/',
		// 'https://www.americancinematheque.com/now-showing/hiroshima-mon-amour-3-22-22/',
		// 'https://www.americancinematheque.com/now-showing/hiroshima-mon-amour-india-song/',
		// 'https://www.americancinematheque.com/now-showing/the-conversation-3-24-22/',
		// 'https://www.americancinematheque.com/now-showing/the-bloody-child-queen-of-diamonds-short-the-great-sadness-of-zohara-march-24-2022/',
		// 'https://www.americancinematheque.com/now-showing/dissolution-march-24-2022/',
		// 'https://www.americancinematheque.com/now-showing/titmouse-5-second-animation-night-3-25-22-7pm/', DELETE
		// 'https://www.americancinematheque.com/now-showing/titmouse-5-second-animation-night-3-25-2022-10pm/', DELETE
		'https://www.americancinematheque.com/now-showing/phantom-love-march-26-2022/',
		'https://www.americancinematheque.com/now-showing/the-conversation-3-26-2022/',
		'https://www.americancinematheque.com/now-showing/goodbye-dragon-inn-3-27-2022/',
		'https://www.americancinematheque.com/now-showing/coming-apart-3-27-2022-2/'
	]
};