module.exports = {
	START_DAY: 16,
	END_DAY: 28,
	EVENT_LIST_CARD_SELECTOR: ".seriesEventCardModule__target",
	SELECTORS: {
		MONTH: 2,
		YEAR: 2022,
		TITLE_SELECTOR: "section.eventHero h1.eventHero__title",
		POSTER_SELECTOR: "section.eventHero figure.eventHero__image > img",
		LOCATION_SELECTOR: "section.eventHero > div > article > div.eventHero__intro > p:nth-child(1)",
		DATE_SELECTOR: "section.eventHero span.eventHero__date",
		TIME_SELECTOR: "section.eventHero span.eventHero__time",
		SINGLE_DESCRIPTION_SELECTOR: "div.eventMain__body > h3 + p",
		SINGLE_DIRECTOR_SELECTOR: "section.eventDetailBar ul.eventDetailBar__list > li:nth-child(3)",
		DOUBLE_FIRST_SELECTOR: "section.eventMain div.eventMain__body > p span:first-child",
		DOUBLE_SECOND_SELECTOR: "section.eventMain div.eventMain__body > hr + p > span:first-child"
	},
	SCREENING_URLS: [
		// 'https://www.americancinematheque.com/now-showing/a-raisin-in-the-sun/',
		// 'https://www.americancinematheque.com/now-showing/speed/',
		// 'https://www.americancinematheque.com/now-showing/all-that-heaven-allows/',
		// 'https://www.americancinematheque.com/now-showing/ali-fear-eats-the-soul/',
		// 'https://www.americancinematheque.com/now-showing/roman-holiday-swept-away-by-an-unusual-destiny-in-the-blue-sea-of-august/',
		// 'https://www.americancinematheque.com/now-showing/hester-street/',
		// 'https://www.americancinematheque.com/now-showing/cinematic-void-presents-death-game/',
		// 'https://www.americancinematheque.com/now-showing/chitty-chitty-bang-bang/',
		// 'https://www.americancinematheque.com/now-showing/invasion-of-the-body-snatchers-2-5-22/',
		// 'https://www.americancinematheque.com/now-showing/women-in-love-the-age-of-innocence/',
		// 'https://www.americancinematheque.com/now-showing/love-streams-2-5-22/',
		// 'https://www.americancinematheque.com/now-showing/rabid-2-5-22/',
		// 'https://www.americancinematheque.com/now-showing/bendavid-grabinski-presents-the-man-who-wasnt-there/',
		// 'https://www.americancinematheque.com/now-showing/the-olive-trees-of-justice-2-6-22/',
		// 'https://www.americancinematheque.com/now-showing/doctor-zhivago-2-6-22/',
		// 'https://www.americancinematheque.com/now-showing/madchen-in-uniform-2-6-22/',
		// 'https://www.americancinematheque.com/now-showing/death-in-venice-2-6-22/',
		// 'https://www.americancinematheque.com/now-showing/cinematic-void-lifeforce-2-7-22/',
		// 'https://www.americancinematheque.com/now-showing/the-olive-trees-of-justice-2-7-22/',
		// 'https://www.americancinematheque.com/now-showing/in-the-heat-of-the-night/',
		// 'https://www.americancinematheque.com/now-showing/play-it-as-it-lays-2-8-22/',
		// 'https://www.americancinematheque.com/now-showing/they-call-me-mister-tibbs-feb922/',
		// 'https://www.americancinematheque.com/now-showing/deep-end-2-9-22/',
		// 'https://www.americancinematheque.com/now-showing/the-thing-called-love-2-10-22/',
		// 'https://www.americancinematheque.com/now-showing/sid-and-nancy-2-10-22/',
		// 'https://www.americancinematheque.com/now-showing/david-and-lisa-2-10-22/',
		// 'https://www.americancinematheque.com/now-showing/play-it-as-it-lays-2-11-22/',
		// 'https://www.americancinematheque.com/now-showing/orlando-2-11-22/',
		// 'https://www.americancinematheque.com/now-showing/fright-night-frights-the-fly-2-11-22/',
		// 'https://www.americancinematheque.com/now-showing/one-million-years-b-c/',
		// 'https://www.americancinematheque.com/now-showing/batman-2-12-22/',
		// 'https://www.americancinematheque.com/now-showing/ladyhawke-2-12-22/',
		// 'https://www.americancinematheque.com/now-showing/etheria-presents-student-body/',
		// 'https://www.americancinematheque.com/now-showing/lone-star-2-13-22/',
		// 'https://www.americancinematheque.com/now-showing/saving-face-2-13-22/',
		// 'https://www.americancinematheque.com/now-showing/wings-of-desire-2-14-22/',
		// 'https://www.americancinematheque.com/now-showing/cinematic-void-presents-fright-night/',
		// 'https://www.americancinematheque.com/now-showing/to-sir-with-love/',
		// 'https://www.americancinematheque.com/now-showing/moonstruck-2-15-22/',
		// 'https://www.americancinematheque.com/now-showing/edge-of-the-city-feb16-22/',
		// 'https://www.americancinematheque.com/now-showing/something-wild-2-16-22/',
		// 'https://www.americancinematheque.com/now-showing/minnie-and-moskowitz/',
		// 'https://www.americancinematheque.com/now-showing/peggy-sue-got-married-2-17-22/',
		// 'https://www.americancinematheque.com/now-showing/betty-blue-2-18-22/',
		// 'https://www.americancinematheque.com/now-showing/maurice-2-18-22/',
		// 'https://www.americancinematheque.com/now-showing/robin-and-the-7-hoods/',
		// 'https://www.americancinematheque.com/now-showing/the-searchers-2-19-22/',
		// 'https://www.americancinematheque.com/now-showing/mmfr/',
		// 'https://www.americancinematheque.com/now-showing/m-butterfly-2-19-22/',
		// 'https://www.americancinematheque.com/now-showing/cane-river-2-20-22/',
		// 'https://www.americancinematheque.com/now-showing/cinematic-void-presents-the-hunger-2-21-22/',
		// 'https://www.americancinematheque.com/now-showing/da-sweet-blood-of-jesus-2-21-22/',
		// 'https://www.americancinematheque.com/now-showing/guess-whos-coming-to-dinner/',
		// 'https://www.americancinematheque.com/now-showing/je-taime-je-taime-2-22-22/',
		'https://www.americancinematheque.com/now-showing/buck-and-the-preacher/',
		'https://www.americancinematheque.com/now-showing/the-childrens-hour-2-23-22/',
		'https://www.americancinematheque.com/now-showing/henry-june-2-24-22/',
		'https://www.americancinematheque.com/now-showing/in-the-realm-of-the-senses-2-24-22/',
		'https://www.americancinematheque.com/now-showing/women-in-love-2-25-22/',
		'https://www.americancinematheque.com/now-showing/legend-2-25-22/',
		'https://www.americancinematheque.com/now-showing/lost-horizon-2-26-22/',
		'https://www.americancinematheque.com/now-showing/the-vampire-bat-2-26-22/',
		'https://www.americancinematheque.com/now-showing/belfast-2-26-22/',
		'https://www.americancinematheque.com/now-showing/king-kong-2-26-22/',
		'https://www.americancinematheque.com/now-showing/the-dead-zone-2-27-22/',
		'https://www.americancinematheque.com/now-showing/in-the-realm-of-the-senses-2-28-22/',
	]
};